Fix: entrantId 필드가 null인 오류
InvalidCastException: Null object cannot be converted to a value type.
오류로 인해 JSON 역직렬화 수행이 안되었음